---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: demo4kafka
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      resources:
        limits:
          memory: "512Mi"
          cpu: "250m"
  restartPolicy: Always
...