server:
  port: 8081

spring:
  application:
    name: kafka-consumer

  kafka:
    consumer:
      group-id: "kafka-consumer"


app:
  tracking-events-topic:
    name: tracking-events
    partitions: 3
    replicas: 1