spring:
  application:
    name: azure-blob-storage

  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources[0]:
            name: azure-kv-property-source
            endpoint: https://azure-blob-kv-abc123.vault.azure.net/

      storage:
        blob:
          account-name: "sbootblobstorage34ff34ab"
          account-key: "${storage-access-key}"

