spring:
  application:
    name: azure-blob-storage

  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources[0]:
            name: azure-kv-property-source
            endpoint: https://az-bstore-432-kv.vault.azure.net/

      storage:
        blob:
          account-name: "azbstore432storage"
          account-key: "${storage-access-key}"

