spring:
  application:
    name: messaging-app

  cloud:
    azure:
      storage:
        queue:
          account-name: messagingviaarm
          queue-name: uploads-notifications

      servicebus:
        namespace: messaging-via-arm-bus
        entity-type: queue
        entity-name: uploads-notifications

  management:
    health:
      azure-storage-blob:
        enabled: false
      azure-storage-fileshare:
        enabled: false
      azure-storage-queue:
        enabled: false